AWSTemplateFormatVersion: 2010-09-09

Description: RDS-template

Resources:
#----------------------------------------------------------
# RDS
#----------------------------------------------------------
 RDS:
   Type: AWS::RDS::DBInstance
   Properties:
     AvailabilityZone: ap-northeast-1a
     DBInstanceIdentifier: lecture10-database
     DBSubnetGroupName: !Ref RDSSubnetGroup
     DBInstanceClass: db.t3.micro
     AllocatedStorage: 20
     Engine: mysql
     MasterUsername: admin
     MasterUserPassword: lecture10
     CopyTagsToSnapshot: false
     DeleteAutomatedBackups: true
     PubliclyAccessible: false
     MultiAZ: false
     VPCSecurityGroups: 
       - !Ref RDSsg
     Tags:
       - Key: Name
         Value: lecture10-database
#----------------------------------------------------------
# RDS Security-Group
#----------------------------------------------------------  
 RDSsg:
   Type: AWS::EC2::SecurityGroup
   Properties:
     GroupName: lecture10-RDS-Security-Group
     GroupDescription: RDS-Security-Group
     VpcId: !ImportValue VPC
     SecurityGroupIngress:
       - IpProtocol: tcp
         FromPort: 3306
         ToPort: 3306
         SourceSecurityGroupId: !ImportValue EC2sg
     Tags:
       - Key: Name
         Value: lecture10rds-sg
#---------------------- ------------------------------------
# RDS Subnet-Group
#----------------------------------------------------------  
 RDSSubnetGroup: 
   Type: AWS::RDS::DBSubnetGroup
   Properties: 
     DBSubnetGroupName: RDS-SubnetGroup
     DBSubnetGroupDescription: lecture10-RDS-Subnet-Group
     SubnetIds:
       - !ImportValue PrivateSubnet1
       - !ImportValue PrivateSubnet2
#----------------------------------------------------------
# Outputs
#----------------------------------------------------------
Outputs:
 RDS:
   Value: !Ref RDS
   Export:
     Name: RDS
  
 RDSsg:
   Value: !Ref RDSsg
   Export:
     Name: RDSsg